import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

import Atas from "@/components/Atas";
import SideDrawer from "@/components/SideDrawer";
import Test from "@/components/Test";
import prisma from "@/lib/prisma";

const inter = Inter({ subsets: ["latin"] });

const getSideMenus = async () => {
    const res = await prisma.side_menu.findMany();
    return res;
};

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default async function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    const menus = await getSideMenus();
    return (
        <html lang="en" data-theme="business">
            <body className={inter.className}>
                <div className="bg-base-200 text-base-content fixed top-0 z-50 flex h-16 w-full justify-center bg-opacity-20 backdrop-blur transition-all duration-100 shadow-sm">
                    <Atas />
                </div>
                <SideDrawer childrenSide={children} sideMenus={menus} />
            </body>
        </html>
    );
}
