import type { Metadata } from "next";

export const metadata: Metadata = {
    title: "User",
    description: "Generated by create next app",
};

export default function UserLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    return (
        <>
            <h2 className="text-5xl font-bold mb-10">Daftar User</h2>
            {children}
            <div className="join">
                <button className="join-item btn">1</button>
                <button className="join-item btn btn-active">2</button>
                <button className="join-item btn">3</button>
                <button className="join-item btn">4</button>
            </div>
        </>
    );
}
